name: weather_app
description: A Weather Task
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  intl: ^0.17.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^6.0.0
  http: ^0.13.5
  dartz: ^0.10.1
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  animate_do: ^2.1.0
  intro_slider: ^3.0.10
  form_builder_validators: ^8.3.0
  progress_state_button: ^1.0.4
  cached_network_image: ^3.2.1
  equatable: ^2.0.5
  flutter_spinkit: ^5.1.0
  shimmer: ^2.0.0
  flutter_svg: ^1.1.4
  firebase_core: ^1.21.1
  firebase_auth: ^3.7.0
  lottie: ^1.4.2
  flutter_google_places: ^0.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  hive_generator: ^1.1.3
  flutter_launcher_icons: ^0.10.0


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
    - assets/font/
    - assets/locales/
    - assets/lottie/
    - assets/svg/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900
